repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        language_version: python3
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v1.9.0
      hooks:
      -   id: reorder-python-imports
          args: [--py3-plus]
