name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tox on ${{ matrix.os }} for Python ${{ matrix.tox.py_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        tox:
          - py_version: '3.6'
            env: py36
          - py_version: '3.7'
            env: py37
          - py_version: '3.8'
            env: py38,flake8,mypy,black
          - py_version: '3.9'
            env: py39
          - py_version: '3.10'
            env: py310
          - py_version: '3.11'
            env: py311
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.tox.py_version }}
          cache: 'pip'
          cache-dependency-path: |
            **/setup.cfg
            **/requirements*.txt
            .tox
      - name: Install tox
        run: python3 -m pip install tox
      - name: Run tox
        run: tox -q -p all -e ${{ matrix.tox.env }}
